#include "test.idl"

module ats {
module scania {

  const uint8 CONSTANT = 1;
  const uint8 CONSTANT2 = (CONSTANT << 2) & CONSTANT;


  struct test {
    map<uint8, map<uint16, sequence<uint32>>, 10> stuff;
  };

  enum my_enum {
    ONE,
    TWO,
    THREE
  };

};
};
